### ISSUE TITLE
Take actual renewal_days from directadmin.conf

### ISSUE THREAD

**Issue by poralix** [Erulezz/directadmin-letsencrypt-show-domains#1]
Hello,

I'd suggest that you take actual renewal_days from directadmin.conf:

```
letsencrypt_renewal_days=`/usr/local/directadmin/directadmin c | grep ^letsencrypt_renewal_days= | cut -d\= -f2`
```

Regards,
Alex.

**Comment by Erulezz** [comment]
Hello Alex,

Thank you, added it to the file: https://github.com/Erulezz/directadmin-letsencrypt-show-domains/commit/4208b30489eb71bcb83cff456b3fa3f750c8ec9c
